CREATE DATABASE IF NOT EXISTS concurso_benet CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE concurso_benet;
CREATE TABLE IF NOT EXISTS pdv (id INT AUTO_INCREMENT PRIMARY KEY, codigo VARCHAR(80) NOT NULL UNIQUE, nombre VARCHAR(255) NOT NULL, comercial VARCHAR(255), zona_supervision VARCHAR(255), ciudad VARCHAR(120), regional VARCHAR(120), activo TINYINT(1) NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS fotos (id INT AUTO_INCREMENT PRIMARY KEY, pdv_id INT NOT NULL, archivo VARCHAR(255) NOT NULL, intento TINYINT NOT NULL, fecha_hora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, seleccionada TINYINT(1) NOT NULL DEFAULT 0, confirmada TINYINT(1) NOT NULL DEFAULT 0, CONSTRAINT fk_foto_pdv FOREIGN KEY (pdv_id) REFERENCES pdv(id) ON DELETE CASCADE);
